plugins {
    id("gradlebuild.distribution.api-java")
}

description = "Public API for build cache configuration types and service factories"

dependencies {
    api(projects.baseServices)
    api(projects.buildCacheSpi)
    api(projects.internalInstrumentationApi)

    api(libs.jspecify)

    implementation(projects.io)
    implementation(projects.stdlibJavaExtensions)

    integTestDistributionRuntimeOnly(projects.distributionsCore)
}

gradleModule {
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        client = true
        daemon = true
        worker = true
    }
}

packageCycles {
    excludePatterns.add("org/gradle/caching/**")
}

errorprone {
    nullawayEnabled = false
}
